com.griddynamics.es.graduation.project:
  esHost: http://localhost:9200
  user:
  pass:
  index: typeaheads

  files:
    mappings: classpath:elastic/typeaheads/mappings.json
    settings: classpath:elastic/typeaheads/settings.json
    bulkData: classpath:elastic/typeaheads/bulk_data.txt

  request:
    default:
      findByQuerySize: 10
      getAllSize: 50
    minQueryLength: 3
    fuzziness:
      startsFromLength:
        one: 4
        two: 6
      boost:
        zero: 1.0
        one: 0.5
        two: 0.25
    prefixQueryBoost: 0.9

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.test: WARN
    org.springframework.boot.test: WARN
    org.elasticsearch.client.RestClient: WARN # TRACE # Or DEBUG, INFO, WARN, ERROR
    org.elasticsearch.client: WARN # TRACE # Or DEBUG, INFO, WARN, ERROR
    org.apache.http.wire: WARN # DEBUG # Or DEBUG, INFO, WARN, ERROR

