spring:
  application:
    name: product-indexer
server:
  port: 8087

com:
  griddynamics:
    product:
      indexer:
        esHost: http://localhost:9200
        user:
        pass:
        index: products
        alias: product_index
        maxIndices: 3

